fixtures:
  forge_modules:
    apt:
      repo: 'puppetlabs/apt'
    concat:
      repo: 'puppetlabs/concat'
    epel: 'stahnma/epel'
    stdlib:
      repo: 'puppetlabs/stdlib'
    yumrepo_core: 'puppetlabs/yumrepo_core'
  symlinks:
    amavisd: "#{source_dir}"
