fixtures:
  forge_modules:
    apt:
      repo: 'puppetlabs/apt'
    concat:
      repo: 'puppetlabs/concat'
    epel: 'stahnma/epel'
    stdlib:
      repo: 'puppetlabs/stdlib'
  symlinks:
    amavisd: "#{source_dir}"
