---
fixtures:
  forge_modules:
    apt:
      repo: 'puppetlabs/apt'
    concat:
      repo: 'puppetlabs/concat'
    epel:
      repo: 'puppet/epel'
    stdlib:
      repo: 'puppetlabs/stdlib'
    yumrepo_core:
      repo: 'puppetlabs/yumrepo_core'
  symlinks:
    amavisd: "#{source_dir}"
