---
appveyor.yml:
  delete: true
.gitignore:
  required:
    - '/.librarian'
    - '/.tmp'
    - '/spec/fixtures/work-dir'
    - '---/doc/'
.gitlab-ci.yml:
  delete: true
Rakefile:
  changelog_project: 'puppet-amavisd'
  changelog_user: 'broadinstitute'
  changelog_version_tag_pattern: '%s'
  extra_disabled_lint_checks:
    - '80chars'
    - 'autoloader_layout'
    - 'puppet_url_without_modules'
  requires:
    - 'puppet-lint/tasks/puppet-lint'
.travis.yml:
  delete: true
.yardopts:
  delete: true
Gemfile:
  optional:
    ':development':
      - gem: 'pdk'
spec/default_facts.yml:
  delete: true
spec/spec_helper.rb:
  coverage_report: true
  hiera_config: 'spec/fixtures/hiera.yaml'
  mock_with: ':rspec'
