---
language: ruby
sudo: false
cache:
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/spec/fixtures/modules
install:
  - bundle install --without development system_tests --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle exec rake spec_prep
before_install: rm Gemfile.lock || true
script: bundle exec rake test
branches:
  only:
  - master
rvm:
- 2.1
- 2.2
- 2.3
- 2.4
env:
  matrix:
  - PUPPET_GEM_VERSION="~> 4.0"
  - PUPPET_GEM_VERSION="~> 5.0"
matrix:
  fast_finish: true
  exclude:
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="~> 5.0"
  - rvm: 2.2
    env: PUPPET_GEM_VERSION="~> 5.0"
