---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: broadinstitute/puppet-amavisd
  description: Puppet module for installing and configuring amavis-new
  name: puppet-amavisd
  tags:
    - amavisd
    - bits
    - bits-tools
    - puppet
  title: puppet-amavisd
spec:
  lifecycle: production
  owner: bits-aviso
  system: puppet
  type: service
